# Generated by Django 4.2.16 on 2025-06-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="addr",
            field=models.CharField(max_length=100, verbose_name="详细地址"),
        ),
        migrations.AlterField(
            model_name="address",
            name="aname",
            field=models.CharField(max_length=30, verbose_name="收货人"),
        ),
        migrations.AlterField(
            model_name="address",
            name="aphone",
            field=models.CharField(max_length=11, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="pwd",
            field=models.CharField(max_length=100, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="uname",
            field=models.CharField(max_length=100, verbose_name="用户名"),
        ),
    ]
