# Generated by Django 4.2.16 on 2025-10-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_alter_address_addr_alter_address_aname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="score",
            field=models.IntegerField(default=100, verbose_name="用户积分"),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
