# Generated by Django 4.2.16 on 2025-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_userinfo_score_delete_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.CharField(
                default="default@163.com", max_length=25, verbose_name="邮箱"
            ),
        ),
    ]
