# Generated by Django 4.2.16 on 2025-10-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0004_userinfo_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="RechargeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "out_trade_no",
                    models.CharField(max_length=64, unique=True, verbose_name="商户订单号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="赠送积分")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "待支付"), (1, "已支付"), (2, "已关闭")], default=0
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("pay_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.userinfo",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "db_table": "recharge_order",
            },
        ),
    ]
