# Generated by Django 4.2.16 on 2025-06-04 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userapp", "0002_alter_address_addr_alter_address_aname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goodid", models.PositiveIntegerField(verbose_name="商品编号")),
                ("colorid", models.PositiveIntegerField(verbose_name="颜色编号")),
                ("sizeid", models.PositiveIntegerField(verbose_name="尺寸编号")),
                ("count", models.PositiveIntegerField(default=0, verbose_name="数量")),
                ("isdelete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.userinfo",
                    ),
                ),
            ],
        ),
    ]
