# Generated by Django 4.2.16 on 2025-06-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="goodid",
            new_name="goodsid",
        ),
    ]
