# Generated by Django 4.2.16 on 2025-06-05 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="out_trade_num",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
